// portfolio/components/footer/footer.tsx
import { Navbar } from "reactstrap";
import styles from "./icons.module.scss";
import ReactDOM from "react-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faFacebookSquare,
  faInstagramSquare,
  faLinkedin,
  faBehanceSquare,
  faArtstation,
  faGithub,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  faFacebookSquare,
  faInstagramSquare,
  faLinkedin,
  faBehanceSquare,
  faArtstation,
  faGithub
);

export default function footer() {
  return (
    <Navbar color="light" expand="md" fixed="bottom">
      <FontAwesomeIcon
        className={styles.icons}
        icon={faFacebookSquare}
        size="lg"
      />
      <FontAwesomeIcon
        className={styles.icons}
        icon={faInstagramSquare}
        size="lg"
      />
      <FontAwesomeIcon className={styles.icons} icon={faLinkedin} size="lg" />
      <FontAwesomeIcon
        className={styles.icons}
        icon={faBehanceSquare}
        size="lg"
      />
      <FontAwesomeIcon className={styles.icons} icon={faArtstation} size="lg" />
      <FontAwesomeIcon className={styles.icons} icon={faGithub} size="lg" />
    </Navbar>
  );
}

// portfolio/src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { faFacebookSquare } from '@fortawesome/free-brands-svg-icons';
import { faInstagramSquare } from '@fortawesome/free-brands-svg-icons';
import { faBehanceSquare } from '@fortawesome/free-brands-svg-icons';
import { faLinkedin } from '@fortawesome/free-brands-svg-icons';
import { faArtstation } from '@fortawesome/free-brands-svg-icons';
import { faGithub } from '@fortawesome/free-brands-svg-icons';



@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {
  facebook = faFacebookSquare;
  instagram = faInstagramSquare;
  linkedin = faLinkedin;
  behance = faBehanceSquare;
  artstation = faArtstation;
  github = faGithub;
  
  constructor() { }

  ngOnInit(): void { 
  }

}

<nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container-fluid">
        <div class="">
            <a href="#">
                <fa-icon [icon]="facebook" size="lg"></fa-icon>
            </a>
            <a href="#">
                <fa-icon [icon]="instagram" size="lg"></fa-icon>
            </a>
            <a href="#">
                <fa-icon [icon]="linkedin" size="lg"></fa-icon>
            </a>
            <a href="#">
                <fa-icon [icon]="behance" size="lg"></fa-icon>
            </a>
            <a href="#">
                <fa-icon [icon]="artstation" size="lg"></fa-icon>
            </a>
            <a href="#">
                <fa-icon [icon]="github" size="lg"></fa-icon>
            </a>
        </div>
        <p class="m-0">@Copyrigh - All rights reserverd. / Caique Matheus - 2021</p>
    </div>
</nav>
